motor_1:
  ID: 101
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
  Goal_Position: -4000
motor_2:
  ID: 110
  Return_Delay_Time: 0
  Operating_Mode: 4
  Profile_Acceleration: 0
  Profile_Velocity: 0
#Goal_Position: 
